# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx # osx nightly is failing: https://github.com/travis-ci/travis-ci/issues/5740
julia:
  - release
  - nightly
notifications:
  email: false
before_script:
  - julia -e 'Pkg.clone("git://github.com/blegat/Polyhedra.jl.git")'
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("cddlib"); Pkg.test("cddlib"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("CDDLib")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
